#!/usr/bin/env python2.7

import sys
import webbrowser
from os import path
from PyQt4.QtCore import *
from PyQt4.QtGui import *
from PyQt4.QtWebKit import *

home      = path.dirname(path.realpath(__file__))
datafile  = path.join(home, 'data.json')
indexfile = path.join(home, 'index.html')

class Storage(QObject):
    "Provides storage to shaman web application"

    @pyqtSlot(result=str)
    def read(self):
        if path.isfile(datafile):
            with open(datafile, 'r+') as f:
                return f.read()
        else: return '[]'

    @pyqtSlot(QString)
    def write(self, value):
        with open(datafile, 'w+') as f:
            f.write(str(value))

class Browser(QObject):
    "Provides ability to open url links"

    @pyqtSlot(QString)
    def open(self, link):
        webbrowser.open(str(link))

class WebPage(QWebPage):
    def javaScriptConsoleMessage(self, msg, line, source):
        print '{}:{} => {}'.format(source, line, msg)

app = QApplication(sys.argv)

page = WebPage()
def bindObjects():
    frame = page.mainFrame()
    frame.addToJavaScriptWindowObject('shamanStorage', Storage())
    frame.addToJavaScriptWindowObject('shamanBrowser', Browser())
page.loadFinished.connect(bindObjects)

web = QWebView()
web.setPage(page)
web.load(QUrl(indexfile))
web.show()

sys.exit(app.exec_())
